/**
 * 
 * 
 * 
 *
 * Created on Apr 12, 2011, 11:24:59 AM
 */

package com.sandy.apps.pluto.ui.dialogmgr.panel.jobsummary;

import com.sandy.apps.pluto.ui.UIConstant ;


/**
 * This panel is the editor for the common job attributes.
 *
 * @author Sandeep Deb [deb.sandeep@gmail.com]
 */
public class JobCommonAttrEditorPanelUI extends javax.swing.JPanel {

    /** Creates new form JobCommonAttrEditorPanelUI */
    public JobCommonAttrEditorPanelUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        this.jLabel1 = new javax.swing.JLabel();
        this.jLabel2 = new javax.swing.JLabel();
        this.jComboBox1 = new javax.swing.JComboBox();
        this.nameTF = new javax.swing.JTextField();
        this.jPanel1 = new javax.swing.JPanel();
        this.cronSecTF = new javax.swing.JTextField();
        this.cronMinTF = new javax.swing.JTextField();
        this.cronHrsTF = new javax.swing.JTextField();
        this.cronDaysMthTF = new javax.swing.JTextField();
        this.cronMthTF = new javax.swing.JTextField();
        this.cronDaysWkTF = new javax.swing.JTextField();
        this.jLabel3 = new javax.swing.JLabel();
        this.jLabel4 = new javax.swing.JLabel();
        this.jLabel5 = new javax.swing.JLabel();
        this.jLabel6 = new javax.swing.JLabel();
        this.jLabel7 = new javax.swing.JLabel();
        this.jLabel8 = new javax.swing.JLabel();
        this.jPanel2 = new javax.swing.JPanel();
        this.jLabel9 = new javax.swing.JLabel();
        this.uctHrsSpinner = new javax.swing.JSpinner();
        this.jLabel10 = new javax.swing.JLabel();
        this.uctMinSpinner = new javax.swing.JSpinner();
        this.jLabel11 = new javax.swing.JLabel();
        this.uctSecSpinner = new javax.swing.JSpinner();
        this.jPanel3 = new javax.swing.JPanel();
        this.jLabel12 = new javax.swing.JLabel();
        this.lctHrsSpinner = new javax.swing.JSpinner();
        this.jLabel13 = new javax.swing.JLabel();
        this.lctMinSpinner = new javax.swing.JSpinner();
        this.jLabel14 = new javax.swing.JLabel();
        this.lctSecSpinner = new javax.swing.JSpinner();
        this.exclHolidaysCB = new javax.swing.JCheckBox();
        this.jScrollPane1 = new javax.swing.JScrollPane();
        this.descrTA = new javax.swing.JTextArea();

        this.jLabel1.setFont(UIConstant.DLG_FONT); // NOI18N
        this.jLabel1.setText("Name");

        this.jLabel2.setFont(UIConstant.DLG_FONT); // NOI18N
        this.jLabel2.setText("Startup Type");

        this.jComboBox1.setFont(UIConstant.DLG_FONT); // NOI18N
        this.jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AUTO", "MANUAL" }));

        this.nameTF.setFont(UIConstant.DLG_FONT); // NOI18N

        this.jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cron settings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N

        this.cronSecTF.setFont(UIConstant.DLG_FONT); // NOI18N

        this.cronMinTF.setFont(UIConstant.DLG_FONT); // NOI18N

        this.cronHrsTF.setFont(UIConstant.DLG_FONT); // NOI18N

        this.cronDaysMthTF.setFont(UIConstant.DLG_FONT); // NOI18N

        this.cronMthTF.setFont(UIConstant.DLG_FONT); // NOI18N

        this.cronDaysWkTF.setFont(UIConstant.DLG_FONT); // NOI18N

        this.jLabel3.setFont(UIConstant.DLG_FONT); // NOI18N
        this.jLabel3.setText("Seconds");

        this.jLabel4.setFont(UIConstant.DLG_FONT); // NOI18N
        this.jLabel4.setText("Minutes");

        this.jLabel5.setFont(UIConstant.DLG_FONT); // NOI18N
        this.jLabel5.setText("Hours");

        this.jLabel6.setFont(UIConstant.DLG_FONT); // NOI18N
        this.jLabel6.setText("Days/MTH");

        this.jLabel7.setFont(UIConstant.DLG_FONT); // NOI18N
        this.jLabel7.setText("Month");

        this.jLabel8.setFont(UIConstant.DLG_FONT); // NOI18N
        this.jLabel8.setText("Days/WK");

        final javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(this.jPanel1);
        this.jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(this.cronSecTF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(this.jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(this.cronMinTF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(this.jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(this.cronHrsTF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(this.jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(this.cronDaysMthTF, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(this.jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(this.cronMthTF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(this.jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(this.jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(this.cronDaysWkTF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {this.cronDaysMthTF, this.cronDaysWkTF, this.cronHrsTF, this.cronMinTF, this.cronMthTF, this.cronSecTF});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(this.cronSecTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(this.cronHrsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(this.cronMinTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(this.cronDaysMthTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(this.cronMthTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(this.cronDaysWkTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(this.jLabel3)
                    .addComponent(this.jLabel8)
                    .addComponent(this.jLabel4)
                    .addComponent(this.jLabel5)
                    .addComponent(this.jLabel6)
                    .addComponent(this.jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        this.jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lower control time", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N

        this.jLabel9.setFont(UIConstant.DLG_FONT); // NOI18N
        this.jLabel9.setText("Hour");

        this.uctHrsSpinner.setFont(UIConstant.DLG_FONT); // NOI18N
        this.uctHrsSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        this.jLabel10.setFont(UIConstant.DLG_FONT); // NOI18N
        this.jLabel10.setText("Min");

        this.uctMinSpinner.setFont(UIConstant.DLG_FONT); // NOI18N
        this.uctMinSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        this.jLabel11.setFont(UIConstant.DLG_FONT); // NOI18N
        this.jLabel11.setText("Sec");

        this.uctSecSpinner.setFont(UIConstant.DLG_FONT); // NOI18N
        this.uctSecSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        final javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(this.jPanel2);
        this.jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(this.jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(this.uctHrsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(this.jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(this.uctMinSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(this.jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(this.uctSecSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(this.jLabel9)
                    .addComponent(this.uctHrsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(this.jLabel10)
                    .addComponent(this.uctMinSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(this.jLabel11)
                    .addComponent(this.uctSecSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {this.uctHrsSpinner, this.uctMinSpinner, this.uctSecSpinner});

        this.jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Upper control time", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N

        this.jLabel12.setFont(UIConstant.DLG_FONT); // NOI18N
        this.jLabel12.setText("Hour");

        this.lctHrsSpinner.setFont(UIConstant.DLG_FONT); // NOI18N
        this.lctHrsSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        this.jLabel13.setFont(UIConstant.DLG_FONT); // NOI18N
        this.jLabel13.setText("Min");

        this.lctMinSpinner.setFont(UIConstant.DLG_FONT); // NOI18N
        this.lctMinSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        this.jLabel14.setFont(UIConstant.DLG_FONT); // NOI18N
        this.jLabel14.setText("Sec");

        this.lctSecSpinner.setFont(UIConstant.DLG_FONT); // NOI18N
        this.lctSecSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        final javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(this.jPanel3);
        this.jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(this.jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(this.lctHrsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(this.jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(this.lctMinSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(this.jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(this.lctSecSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(this.jLabel12)
                    .addComponent(this.lctHrsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(this.jLabel13)
                    .addComponent(this.lctMinSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(this.jLabel14)
                    .addComponent(this.lctSecSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {this.lctHrsSpinner, this.lctMinSpinner, this.lctSecSpinner});

        this.exclHolidaysCB.setFont(UIConstant.DLG_FONT); // NOI18N
        this.exclHolidaysCB.setText("Exclude holidays?");

        this.descrTA.setColumns(20);
        this.descrTA.setFont(UIConstant.DLG_FONT); // NOI18N
        this.descrTA.setRows(5);
        this.jScrollPane1.setViewportView(this.descrTA);

        final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(this.exclHolidaysCB)
                    .addComponent(this.jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(this.jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(this.jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(this.jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(this.jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(this.jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64))
                            .addComponent(this.nameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)))
                    .addComponent(this.jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(this.jLabel1)
                    .addComponent(this.nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(this.jLabel2)
                    .addComponent(this.jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(this.jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(this.jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(this.jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(this.exclHolidaysCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(this.jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>


    // Variables declaration - do not modify
    protected javax.swing.JTextField cronDaysMthTF;
    protected javax.swing.JTextField cronDaysWkTF;
    protected javax.swing.JTextField cronHrsTF;
    protected javax.swing.JTextField cronMinTF;
    protected javax.swing.JTextField cronMthTF;
    protected javax.swing.JTextField cronSecTF;
    protected javax.swing.JTextArea descrTA;
    protected javax.swing.JCheckBox exclHolidaysCB;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JSpinner lctHrsSpinner;
    protected javax.swing.JSpinner lctMinSpinner;
    protected javax.swing.JSpinner lctSecSpinner;
    protected javax.swing.JTextField nameTF;
    protected javax.swing.JSpinner uctHrsSpinner;
    protected javax.swing.JSpinner uctMinSpinner;
    protected javax.swing.JSpinner uctSecSpinner;
    // End of variables declaration

}
