/**
 * Creation Date: Aug 18, 2008
 */

package com.sandy.apps.pluto.shared.dto;

import java.util.Calendar ;
import java.util.Date ;

import com.sandy.apps.pluto.shared.EventType ;
import com.sandy.apps.pluto.shared.event.EventBus ;

/**
 * This class encapsulates information regarding a log message generated by
 * the system. Please not that this log message is quite different from the
 * log4j message. The log4j message is for the system administrator while
 * this log message is for the visual display to the end user.
 *
 * @author Sandeep Deb [deb.sandeep@gmail.com]
 */
public class LogMsg {

    /** A static enumeration denoting the severity of the log message. */
    public static enum Sev {
       ERROR, INFO, WARN
    } ;

    private String message = null ;
    private Date   time    = null ;
    private Sev    sev     = null ;

    /** Public constructor. */
    private LogMsg( final Sev sev, final String msg ) {
        super() ;
        this.time = Calendar.getInstance().getTime() ;
        this.message = msg ;
        this.sev = sev ;
    }

    public String getMessage() { return this.message ; }
    public Date getTime() { return this.time ; }
    public Sev getSev() { return this.sev ; }

    /** Static ease of use operation to generate a INFO severity message. */
    public static void info( final String message ) {
        EventBus.publish( EventType.MSG, new LogMsg( Sev.INFO, message ) ) ;
    }

    /** Static ease of use operation to generate a WARN severity message. */
    public static void warn( final String message ) {
        EventBus.publish( EventType.MSG, new LogMsg( Sev.WARN, message ) ) ;
    }

    /** Static ease of use operation to generate a INFO severity message. */
    public static void error( final String message ) {
        EventBus.publish( EventType.MSG, new LogMsg( Sev.ERROR, message ) ) ;
    }
}
